apiVersion: v1
kind: Service
metadata:
  name: shopping-microservice
  labels:
    app: shopping-microservice
spec:
  ports:
  - port: 80
    protocol: TCP
  clusterIP: None
  selector:
    app: shopping-microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-microservice
  labels:
    app: shopping-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-microservice
  template:
    metadata:
      labels:
        app: shopping-microservice
    spec:
      containers:
      - name: shopping-microservice
        image: prabh/shopping-microservice
