apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: shopping-microservice
build:
  artifacts:
  - image: prabh/shopping-microservice
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml